# -*- coding: utf-8 -*-
"""15. basic chat bot .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUvlEu69oEUCG4Y8mLx9C3hyArW22cT2
"""



# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Basic Chatbot")

# Store chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display previous messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# User input
user_input = st.chat_input("Type your message...")

if user_input:
    # Show user message
    st.session_state.messages.append(
        {"role": "user", "content": user_input}
    )

    with st.chat_message("user"):
        st.write(user_input)

    # Simple chatbot logic
    if "hello" in user_input.lower():
        bot_reply = "Hello! How can I help you?"
    elif "name" in user_input.lower():
        bot_reply = "I am a simple Streamlit chatbot."
    elif "bye" in user_input.lower():
        bot_reply = "Goodbye! Have a great day."
    else:
        bot_reply = "Sorry, I don't understand that yet."

    # Show bot response
    st.session_state.messages.append(
        {"role": "assistant", "content": bot_reply}
    )

    with st.chat_message("assistant"):
        st.write(bot_reply)