{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "931a315e-c692-4069-aa3d-8eb5ed3bc487",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\bailw\\anaconda3\\lib\\site-packages (1.45.1)Note: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (8.1.8)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (2.1.3)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (2.2.3)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (11.1.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (19.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (9.0.0)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (4.12.2)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (2.22.1)\n",
      "Requirement already satisfied: colorama in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2026.6.17)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\bailw\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d4e03ac-8db1-4d48-a050-20c69b917daf",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "32d33fc7-cf12-4a44-b5d8-4f2d42294627",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "st.title(\"AI-Powered E-Commerce Analytics Platform\")\n",
    "\n",
    "st.write(\"Welcome to my Final Year Project.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c1985e8-2678-42a8-8a51-a24afcf71109",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "583e9156-3de5-477b-ac86-23ce0c09696b",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.title(\"...\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ebb4fc36-6e4f-4159-ab43-a2a76eb4f202",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"AI E-Commerce Analytics\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"📊 AI-Powered E-Commerce Analytics Platform\")\n",
    "\n",
    "st.subheader(\"Final Year Data Science Project\")\n",
    "\n",
    "st.write(\"\"\"\n",
    "This application helps businesses analyze sales,\n",
    "customer behaviour, and future sales prediction.\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a6e26c70-5afd-488d-a0f8-7f6027116a4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.title(\"Title\")\n",
    "st.header(\"Header\")\n",
    "st.subheader(\"Sub Header\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5b87f9b-1898-4260-ade5-ca0199d6e0fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.write(\"Hello\")\n",
    "st.text(\"Hello\")\n",
    "st.markdown(\"**Bold Text**\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8df28879-bba9-4dc7-8eaf-4a14390e934e",
   "metadata": {},
   "outputs": [],
   "source": [
    "if st.button(\"Click Me\"):\n",
    "    st.success(\"Button Pressed\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a735ee6e-1902-45f6-926e-de9345b444de",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.image(\"assets/home_banner.jpg\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1705802c-9f21-413d-9fc3-0f3375ad3db0",
   "metadata": {},
   "outputs": [],
   "source": [
    "uploaded_file = st.file_uploader(\n",
    "    \"Upload CSV\",\n",
    "    type=[\"csv\"]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "001fd62e-23ac-4604-ba17-979a9dc5b29a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(uploaded_file)\n",
    "\n",
    "st.dataframe(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a45b0a18-29a2-4399-aabc-0c46bf8a8e02",
   "metadata": {},
   "outputs": [],
   "source": [
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "col1.metric(\"Sales\", \"₹5,20,000\")\n",
    "col2.metric(\"Orders\", \"580\")\n",
    "col3.metric(\"Customers\", \"320\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7bbac394-bb88-4cc4-9e50-c81f21b76c1c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "# Page Configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"AI E-Commerce Analytics\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Title\n",
    "st.title(\"📊 AI-Powered E-Commerce Analytics Platform\")\n",
    "\n",
    "# Subtitle\n",
    "st.subheader(\"Final Year Data Science Project\")\n",
    "\n",
    "# Description\n",
    "st.write(\"\"\"\n",
    "Welcome to the AI-Powered E-Commerce Analytics Platform.\n",
    "\n",
    "This application helps businesses:\n",
    "- 📈 Analyze Sales\n",
    "- 👥 Understand Customer Behavior\n",
    "- 📦 Monitor Product Performance\n",
    "- 🤖 Predict Future Sales\n",
    "- 📊 Generate Business Insights\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe7d93f0-7533-4507-b81b-f4a1a30e86f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.title()\n",
    "st.button()\n",
    "st.image()\n",
    "st.dataframe()\n",
    "st.metric()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa49d1bd-221f-4a7a-a2e1-b39b5e188fd6",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.set_page_config(...)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc9ddba2-4e6f-4a54-b21b-030025642519",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.title()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f424746f-636a-42d1-bc02-da2dad5c938d",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.subheader()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6898b2d-e556-415e-9475-42f9bcdc4514",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.write()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16c4df7b-3a85-4a43-9cc4-3eced3ede62f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "# ------------------------------\n",
    "# Page Configuration\n",
    "# ------------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"AI E-Commerce Analytics\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# ------------------------------\n",
    "# Hero Section\n",
    "# ------------------------------\n",
    "\n",
    "col1, col2 = st.columns([2,1])\n",
    "\n",
    "with col1:\n",
    "\n",
    "    st.title(\"📊 AI-Powered E-Commerce Analytics Platform\")\n",
    "\n",
    "    st.subheader(\"Transform Business Data into Actionable Insights\")\n",
    "\n",
    "    st.write(\"\"\"\n",
    "    Welcome to the **AI-Powered E-Commerce Analytics Platform**.\n",
    "\n",
    "    This application helps businesses:\n",
    "\n",
    "    ✅ Analyze Sales\n",
    "\n",
    "    ✅ Understand Customer Behaviour\n",
    "\n",
    "    ✅ Monitor Product Performance\n",
    "\n",
    "    ✅ Predict Future Sales\n",
    "\n",
    "    ✅ Generate Business Insights\n",
    "\n",
    "    ✅ Build Interactive Dashboards\n",
    "    \"\"\")\n",
    "\n",
    "    col_btn1, col_btn2 = st.columns(2)\n",
    "\n",
    "    with col_btn1:\n",
    "        st.button(\"📂 Upload Dataset\")\n",
    "\n",
    "    with col_btn2:\n",
    "        st.button(\"📈 Explore Dashboard\")\n",
    "\n",
    "\n",
    "with col2:\n",
    "\n",
    "    st.image(\n",
    "        \"https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=600\",\n",
    "        use_container_width=True\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d32c3d5a-862d-4ed8-82b9-f3c6ac389b36",
   "metadata": {},
   "outputs": [],
   "source": [
    "col1, col2 = st.columns([2,1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "abded613-04c3-44c2-9b4f-d3d7d5b6726f",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.button(\"Upload Dataset\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de1781b6-5ec4-45fa-a9c5-0fad03377881",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.image(...)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b172457a-5005-4475-9ec5-066687198888",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================\n",
    "# Quick Business Overview\n",
    "# ==========================================\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.header(\"📊 Quick Business Overview\")\n",
    "\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "\n",
    "with col1:\n",
    "    st.metric(\n",
    "        label=\"💰 Total Sales\",\n",
    "        value=\"₹5,48,200\",\n",
    "        delta=\"12%\"\n",
    "    )\n",
    "\n",
    "with col2:\n",
    "    st.metric(\n",
    "        label=\"📦 Total Orders\",\n",
    "        value=\"350\",\n",
    "        delta=\"18\"\n",
    "    )\n",
    "\n",
    "with col3:\n",
    "    st.metric(\n",
    "        label=\"👥 Customers\",\n",
    "        value=\"185\",\n",
    "        delta=\"7\"\n",
    "    )\n",
    "\n",
    "with col4:\n",
    "    st.metric(\n",
    "        label=\"📈 Profit\",\n",
    "        value=\"₹82,650\",\n",
    "        delta=\"8%\"\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06e0ea22-f3d8-4230-abc7-589f97c1919c",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.metric(\n",
    "    label=\"Total Sales\",\n",
    "    value=\"₹500000\",\n",
    "    delta=\"12%\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23fb63ac-2cfd-40a4-8b7e-23b180dc6df8",
   "metadata": {},
   "outputs": [],
   "source": [
    "delta=\"-5%\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3e6598c-e0d0-4f25-a059-3245297386f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "value=\"₹5,48,200\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4cef4c65-3137-4630-b5bd-d594ae810c2a",
   "metadata": {},
   "outputs": [],
   "source": [
    "value=f\"₹{df['Sales'].sum():,.0f}\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2cd5f90-c39e-4da4-872b-eb44ce011a60",
   "metadata": {},
   "outputs": [],
   "source": [
    "Total Orders"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6b65b46d-5820-4921-892b-95ddab64bd4a",
   "metadata": {},
   "outputs": [],
   "source": [
    "len(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8cef115c-9ea1-46ee-9a73-bca2feec52ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"Customer ID\"].nunique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8644c1ed-6b50-4a5e-bb94-6352f52fba42",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"Profit\"].sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "563cf515-be14-4ace-92d4-b52c42de9f1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.markdown(\"---\")\n",
    "st.header(\"🚀 Explore Features\")\n",
    "\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "with col1:\n",
    "    st.info(\"\"\"\n",
    "    📂 Upload Dataset\n",
    "\n",
    "    Upload CSV or Excel files for analysis.\n",
    "    \"\"\")\n",
    "\n",
    "with col2:\n",
    "    st.info(\"\"\"\n",
    "    📈 Exploratory Data Analysis\n",
    "\n",
    "    Visualize trends and business performance.\n",
    "    \"\"\")\n",
    "\n",
    "with col3:\n",
    "    st.info(\"\"\"\n",
    "    🤖 AI Business Assistant\n",
    "\n",
    "    Ask questions about your data.\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "col4, col5, col6 = st.columns(3)\n",
    "\n",
    "with col4:\n",
    "    st.info(\"\"\"\n",
    "    📉 Sales Forecasting\n",
    "\n",
    "    Predict future sales using Machine Learning.\n",
    "    \"\"\")\n",
    "\n",
    "with col5:\n",
    "    st.info(\"\"\"\n",
    "    🗄 MySQL Integration\n",
    "\n",
    "    Store and query your business data.\n",
    "    \"\"\")\n",
    "\n",
    "with col6:\n",
    "    st.info(\"\"\"\n",
    "    📄 Business Reports\n",
    "\n",
    "    Generate professional reports.\n",
    "    \"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12096b9b-387f-4b18-93aa-c7b8e23cdcac",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from config import APP_NAME, PAGE_ICON, AUTHOR, VERSION\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=APP_NAME,\n",
    "    page_icon=PAGE_ICON,\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# Load CSS\n",
    "# ==========================================\n",
    "\n",
    "def load_css():\n",
    "    with open(\"assets/style.css\") as f:\n",
    "        st.markdown(f\"<style>{f.read()}</style>\", unsafe_allow_html=True)\n",
    "\n",
    "load_css()\n",
    "\n",
    "# ==========================================\n",
    "# Session State\n",
    "# ==========================================\n",
    "\n",
    "if \"dataset_uploaded\" not in st.session_state:\n",
    "    st.session_state.dataset_uploaded = False\n",
    "\n",
    "# ==========================================\n",
    "# Sidebar\n",
    "# ==========================================\n",
    "\n",
    "with st.sidebar:\n",
    "\n",
    "    st.title(\"📊 AI Analytics\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    st.success(\"Project Status\")\n",
    "\n",
    "    st.progress(0)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    st.write(\"### 👨‍💻 Developer\")\n",
    "\n",
    "    st.write(AUTHOR)\n",
    "\n",
    "    st.write(f\"Version : {VERSION}\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    st.info(\"\"\"\n",
    "Welcome!\n",
    "\n",
    "Use the navigation menu on the left to explore every module of the project.\n",
    "\"\"\")\n",
    "\n",
    "# ==========================================\n",
    "# Main Screen\n",
    "# ==========================================\n",
    "\n",
    "st.title(APP_NAME)\n",
    "\n",
    "st.subheader(\"AI-Powered E-Commerce Analytics & Sales Forecasting Platform\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "👈 Select any module from the left sidebar to begin.\n",
    "\n",
    "Modules include:\n",
    "\n",
    "• Home\n",
    "\n",
    "• Upload Dataset\n",
    "\n",
    "• Data Understanding\n",
    "\n",
    "• Data Cleaning\n",
    "\n",
    "• Exploratory Data Analysis\n",
    "\n",
    "• KPI Dashboard\n",
    "\n",
    "• AI Business Assistant\n",
    "\n",
    "• Sales Forecasting\n",
    "\n",
    "• MySQL Integration\n",
    "\n",
    "• About Project\n",
    "\"\"\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "st.caption(\"© 2026 Deepak Bailwal | Final Year Data Science Project\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68020ccf-8225-4696-9773-3fb84cd640ad",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "414c9af4-4b9f-49cf-813b-54ef28552dd2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3c2adc6-8c8a-4b83-b06a-4a81293134a6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f8a4e0ac-0798-4bcf-af5a-7b764c5d0cf4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78096bdb-eff8-4f22-bd66-a9a06ec5ad35",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6858f1f2-a007-461e-88f5-d3bcbda4afbd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0a80e4c-2415-47cb-9d14-76bc3ce0b852",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# -----------------------------\n",
    "# Page Configuration\n",
    "# -----------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Home\",\n",
    "    page_icon=\"🏠\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "# Load Dataset\n",
    "# -----------------------------\n",
    "DATA_PATH = \"data/ecommerce.csv\"\n",
    "\n",
    "if os.path.exists(DATA_PATH):\n",
    "    df = pd.read_csv(DATA_PATH)\n",
    "\n",
    "    total_sales = df[\"Sales\"].sum()\n",
    "    total_profit = df[\"Profit\"].sum()\n",
    "    total_orders = len(df)\n",
    "    total_customers = df[\"Customer ID\"].nunique()\n",
    "\n",
    "else:\n",
    "    df = None\n",
    "    total_sales = 0\n",
    "    total_profit = 0\n",
    "    total_orders = 0\n",
    "    total_customers = 0\n",
    "\n",
    "# -----------------------------\n",
    "# Hero Section\n",
    "# -----------------------------\n",
    "\n",
    "st.title(\"📊 AI-Powered E-Commerce Analytics Platform\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "Analyze your business performance with interactive dashboards,\n",
    "AI-powered insights, customer analytics, sales forecasting,\n",
    "and MySQL integration.\n",
    "\"\"\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# -----------------------------\n",
    "# KPI Cards\n",
    "# -----------------------------\n",
    "\n",
    "c1, c2, c3, c4 = st.columns(4)\n",
    "\n",
    "c1.metric(\n",
    "    \"💰 Total Sales\",\n",
    "    f\"${total_sales:,.2f}\"\n",
    ")\n",
    "\n",
    "c2.metric(\n",
    "    \"📈 Total Profit\",\n",
    "    f\"${total_profit:,.2f}\"\n",
    ")\n",
    "\n",
    "c3.metric(\n",
    "    \"📦 Orders\",\n",
    "    total_orders\n",
    ")\n",
    "\n",
    "c4.metric(\n",
    "    \"👥 Customers\",\n",
    "    total_customers\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# -----------------------------\n",
    "# Dataset Preview\n",
    "# -----------------------------\n",
    "\n",
    "st.subheader(\"📄 Dataset Preview\")\n",
    "\n",
    "if df is not None:\n",
    "\n",
    "    st.dataframe(\n",
    "        df.head(10),\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "else:\n",
    "\n",
    "    st.warning(\"No dataset found inside data folder.\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# -----------------------------\n",
    "# Application Modules\n",
    "# -----------------------------\n",
    "\n",
    "st.subheader(\"🚀 Available Modules\")\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "\n",
    "    st.success(\"✔ Upload Dataset\")\n",
    "\n",
    "    st.success(\"✔ Data Understanding\")\n",
    "\n",
    "    st.success(\"✔ Data Cleaning\")\n",
    "\n",
    "    st.success(\"✔ Exploratory Data Analysis\")\n",
    "\n",
    "    st.success(\"✔ KPI Dashboard\")\n",
    "\n",
    "with col2:\n",
    "\n",
    "    st.success(\"✔ AI Business Assistant\")\n",
    "\n",
    "    st.success(\"✔ Sales Forecasting\")\n",
    "\n",
    "    st.success(\"✔ MySQL Integration\")\n",
    "\n",
    "    st.success(\"✔ Download Reports\")\n",
    "\n",
    "    st.success(\"✔ About Project\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa80a3c7-cc1f-43e8-8c33-7bda1b5539d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# -----------------------------\n",
    "# Page Configuration\n",
    "# -----------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Home\",\n",
    "    page_icon=\"🏠\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "# Load Dataset\n",
    "# -----------------------------\n",
    "DATA_PATH = \"data/ecommerce.csv\"\n",
    "\n",
    "if os.path.exists(DATA_PATH):\n",
    "    df = pd.read_csv(DATA_PATH)\n",
    "\n",
    "    total_sales = df[\"Sales\"].sum()\n",
    "    total_profit = df[\"Profit\"].sum()\n",
    "    total_orders = len(df)\n",
    "    total_customers = df[\"Customer ID\"].nunique()\n",
    "\n",
    "else:\n",
    "    df = None\n",
    "    total_sales = 0\n",
    "    total_profit = 0\n",
    "    total_orders = 0\n",
    "    total_customers = 0\n",
    "\n",
    "# -----------------------------\n",
    "# Hero Section\n",
    "# -----------------------------\n",
    "\n",
    "st.title(\"📊 AI-Powered E-Commerce Analytics Platform\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "Analyze your business performance with interactive dashboards,\n",
    "AI-powered insights, customer analytics, sales forecasting,\n",
    "and MySQL integration.\n",
    "\"\"\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# -----------------------------\n",
    "# KPI Cards\n",
    "# -----------------------------\n",
    "\n",
    "c1, c2, c3, c4 = st.columns(4)\n",
    "\n",
    "c1.metric(\n",
    "    \"💰 Total Sales\",\n",
    "    f\"${total_sales:,.2f}\"\n",
    ")\n",
    "\n",
    "c2.metric(\n",
    "    \"📈 Total Profit\",\n",
    "    f\"${total_profit:,.2f}\"\n",
    ")\n",
    "\n",
    "c3.metric(\n",
    "    \"📦 Orders\",\n",
    "    total_orders\n",
    ")\n",
    "\n",
    "c4.metric(\n",
    "    \"👥 Customers\",\n",
    "    total_customers\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# -----------------------------\n",
    "# Dataset Preview\n",
    "# -----------------------------\n",
    "\n",
    "st.subheader(\"📄 Dataset Preview\")\n",
    "\n",
    "if df is not None:\n",
    "\n",
    "    st.dataframe(\n",
    "        df.head(10),\n",
    "        use_container_width=True\n",
    "    )\n",
    "\n",
    "else:\n",
    "\n",
    "    st.warning(\"No dataset found inside data folder.\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# -----------------------------\n",
    "# Application Modules\n",
    "# -----------------------------\n",
    "\n",
    "st.subheader(\"🚀 Available Modules\")\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "\n",
    "    st.success(\"✔ Upload Dataset\")\n",
    "\n",
    "    st.success(\"✔ Data Understanding\")\n",
    "\n",
    "    st.success(\"✔ Data Cleaning\")\n",
    "\n",
    "    st.success(\"✔ Exploratory Data Analysis\")\n",
    "\n",
    "    st.success(\"✔ KPI Dashboard\")\n",
    "\n",
    "with col2:\n",
    "\n",
    "    st.success(\"✔ AI Business Assistant\")\n",
    "\n",
    "    st.success(\"✔ Sales Forecasting\")\n",
    "\n",
    "    st.success(\"✔ MySQL Integration\")\n",
    "\n",
    "    st.success(\"✔ Download Reports\")\n",
    "\n",
    "    st.success(\"✔ About Project\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de36a8ad-ee1a-4d1a-8221-33906c4dded1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Data Understanding\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"📊 Data Understanding\")\n",
    "\n",
    "st.write(\n",
    "    \"Explore the structure, quality, and summary of your dataset.\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Load Dataset\n",
    "# ==========================================\n",
    "\n",
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"]\n",
    "\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")\n",
    "\n",
    "else:\n",
    "    st.warning(\"Please upload a dataset first.\")\n",
    "    st.stop()\n",
    "\n",
    "# ==========================================\n",
    "# Basic Information\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"📌 Basic Information\")\n",
    "\n",
    "c1, c2, c3, c4 = st.columns(4)\n",
    "\n",
    "c1.metric(\"Rows\", df.shape[0])\n",
    "c2.metric(\"Columns\", df.shape[1])\n",
    "c3.metric(\"Missing Values\", df.isna().sum().sum())\n",
    "c4.metric(\"Duplicate Rows\", df.duplicated().sum())\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Dataset Preview\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"👀 Dataset Preview\")\n",
    "\n",
    "st.dataframe(df.head(10), use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Column Details\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"📋 Column Information\")\n",
    "\n",
    "column_info = pd.DataFrame({\n",
    "    \"Column\": df.columns,\n",
    "    \"Data Type\": df.dtypes.astype(str),\n",
    "    \"Missing Values\": df.isnull().sum().values,\n",
    "    \"Unique Values\": df.nunique().values\n",
    "})\n",
    "\n",
    "st.dataframe(column_info, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Statistical Summary\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"📈 Statistical Summary\")\n",
    "\n",
    "st.dataframe(df.describe(include=\"all\").T, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Missing Values\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"❌ Missing Value Analysis\")\n",
    "\n",
    "missing_df = pd.DataFrame({\n",
    "    \"Column\": df.columns,\n",
    "    \"Missing Values\": df.isnull().sum().values,\n",
    "    \"Percentage\": (\n",
    "        df.isnull().sum() / len(df) * 100\n",
    "    ).round(2).values\n",
    "})\n",
    "\n",
    "st.dataframe(missing_df, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Duplicate Records\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"🔁 Duplicate Records\")\n",
    "\n",
    "duplicates = df[df.duplicated()]\n",
    "\n",
    "if duplicates.empty:\n",
    "    st.success(\"No duplicate records found.\")\n",
    "else:\n",
    "    st.warning(f\"{len(duplicates)} duplicate rows found.\")\n",
    "    st.dataframe(duplicates, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Memory Usage\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"💾 Memory Usage\")\n",
    "\n",
    "memory = (\n",
    "    df.memory_usage(deep=True)\n",
    "      .sum() / 1024**2\n",
    ")\n",
    "\n",
    "st.info(f\"Dataset Memory Usage : {memory:.2f} MB\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Column Selector\n",
    "# ==========================================\n",
    "\n",
    "st.header(\"🔍 Explore Individual Columns\")\n",
    "\n",
    "selected = st.selectbox(\n",
    "    \"Select a Column\",\n",
    "    df.columns\n",
    ")\n",
    "\n",
    "st.write(\"### Sample Values\")\n",
    "\n",
    "st.write(df[selected].head(20))\n",
    "\n",
    "st.write(\"### Unique Values\")\n",
    "\n",
    "st.write(df[selected].unique()[:20])\n",
    "\n",
    "st.write(\"Total Unique Values :\", df[selected].nunique())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "65747ce6-83d7-46be-b3c1-fd242cbb0f29",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Data Cleaning\",\n",
    "    page_icon=\"🧹\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"🧹 Data Cleaning\")\n",
    "\n",
    "st.write(\n",
    "    \"Clean and prepare your dataset for analysis.\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Load Dataset\n",
    "# ==========================================\n",
    "\n",
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"].copy()\n",
    "\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")\n",
    "\n",
    "else:\n",
    "    st.warning(\"Please upload a dataset first.\")\n",
    "    st.stop()\n",
    "\n",
    "# ==========================================\n",
    "# Original Dataset\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"Original Dataset\")\n",
    "\n",
    "st.dataframe(df.head(), use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Missing Values\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"❌ Missing Values\")\n",
    "\n",
    "missing = df.isnull().sum()\n",
    "\n",
    "st.dataframe(\n",
    "    pd.DataFrame({\n",
    "        \"Column\": missing.index,\n",
    "        \"Missing Values\": missing.values\n",
    "    }),\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# Fill Missing Values\n",
    "fill_option = st.selectbox(\n",
    "    \"Fill Numeric Missing Values Using\",\n",
    "    [\n",
    "        \"Do Nothing\",\n",
    "        \"Mean\",\n",
    "        \"Median\",\n",
    "        \"Mode\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "if fill_option != \"Do Nothing\":\n",
    "\n",
    "    numeric_cols = df.select_dtypes(include=np.number).columns\n",
    "\n",
    "    for col in numeric_cols:\n",
    "\n",
    "        if fill_option == \"Mean\":\n",
    "            df[col] = df[col].fillna(df[col].mean())\n",
    "\n",
    "        elif fill_option == \"Median\":\n",
    "            df[col] = df[col].fillna(df[col].median())\n",
    "\n",
    "        elif fill_option == \"Mode\":\n",
    "            df[col] = df[col].fillna(df[col].mode()[0])\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Remove Duplicates\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"🔁 Duplicate Records\")\n",
    "\n",
    "duplicates = df.duplicated().sum()\n",
    "\n",
    "st.metric(\"Duplicate Rows\", duplicates)\n",
    "\n",
    "if st.button(\"Remove Duplicate Rows\"):\n",
    "\n",
    "    df = df.drop_duplicates()\n",
    "\n",
    "    st.success(\"Duplicate rows removed.\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# String Cleaning\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"🔤 String Cleaning\")\n",
    "\n",
    "text_columns = df.select_dtypes(include=\"object\").columns.tolist()\n",
    "\n",
    "if text_columns:\n",
    "\n",
    "    selected_column = st.selectbox(\n",
    "        \"Select Text Column\",\n",
    "        text_columns\n",
    "    )\n",
    "\n",
    "    if st.button(\"Trim Spaces\"):\n",
    "\n",
    "        df[selected_column] = (\n",
    "            df[selected_column]\n",
    "            .astype(str)\n",
    "            .str.strip()\n",
    "        )\n",
    "\n",
    "        st.success(\"Spaces removed.\")\n",
    "\n",
    "    if st.button(\"Convert to Title Case\"):\n",
    "\n",
    "        df[selected_column] = (\n",
    "            df[selected_column]\n",
    "            .astype(str)\n",
    "            .str.title()\n",
    "        )\n",
    "\n",
    "        st.success(\"Converted to Title Case.\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Outlier Detection\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"📈 Outlier Detection\")\n",
    "\n",
    "numeric_columns = df.select_dtypes(include=np.number).columns.tolist()\n",
    "\n",
    "selected_numeric = st.selectbox(\n",
    "    \"Select Numeric Column\",\n",
    "    numeric_columns\n",
    ")\n",
    "\n",
    "Q1 = df[selected_numeric].quantile(0.25)\n",
    "Q3 = df[selected_numeric].quantile(0.75)\n",
    "\n",
    "IQR = Q3 - Q1\n",
    "\n",
    "lower = Q1 - 1.5 * IQR\n",
    "upper = Q3 + 1.5 * IQR\n",
    "\n",
    "outliers = df[\n",
    "    (df[selected_numeric] < lower)\n",
    "    |\n",
    "    (df[selected_numeric] > upper)\n",
    "]\n",
    "\n",
    "st.metric(\n",
    "    \"Outliers Found\",\n",
    "    len(outliers)\n",
    ")\n",
    "\n",
    "if st.checkbox(\"Show Outliers\"):\n",
    "\n",
    "    st.dataframe(outliers)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Cleaned Dataset\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"✅ Cleaned Dataset\")\n",
    "\n",
    "st.dataframe(\n",
    "    df.head(),\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# Save cleaned dataframe\n",
    "\n",
    "st.session_state[\"df\"] = df\n",
    "\n",
    "# ==========================================\n",
    "# Download\n",
    "# ==========================================\n",
    "\n",
    "csv = df.to_csv(index=False).encode()\n",
    "\n",
    "st.download_button(\n",
    "    \"⬇ Download Cleaned Dataset\",\n",
    "    csv,\n",
    "    \"cleaned_dataset.csv\",\n",
    "    \"text/csv\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa551c6b-753f-460d-8355-1df58aee3d26",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import os\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Exploratory Data Analysis\",\n",
    "    page_icon=\"📈\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"📈 Exploratory Data Analysis\")\n",
    "\n",
    "st.markdown(\n",
    "    \"Visualize trends, discover patterns, and gain insights from your dataset.\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Load Dataset\n",
    "# ==========================================\n",
    "\n",
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"]\n",
    "\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")\n",
    "\n",
    "else:\n",
    "    st.warning(\"Please upload a dataset first.\")\n",
    "    st.stop()\n",
    "\n",
    "# ==========================================\n",
    "# Sidebar Filters\n",
    "# ==========================================\n",
    "\n",
    "st.sidebar.header(\"Filters\")\n",
    "\n",
    "filtered_df = df.copy()\n",
    "\n",
    "# Category Filter\n",
    "if \"Category\" in df.columns:\n",
    "    categories = st.sidebar.multiselect(\n",
    "        \"Category\",\n",
    "        df[\"Category\"].unique(),\n",
    "        default=df[\"Category\"].unique()\n",
    "    )\n",
    "\n",
    "    filtered_df = filtered_df[\n",
    "        filtered_df[\"Category\"].isin(categories)\n",
    "    ]\n",
    "\n",
    "# Region Filter\n",
    "if \"Region\" in df.columns:\n",
    "    regions = st.sidebar.multiselect(\n",
    "        \"Region\",\n",
    "        filtered_df[\"Region\"].unique(),\n",
    "        default=filtered_df[\"Region\"].unique()\n",
    "    )\n",
    "\n",
    "    filtered_df = filtered_df[\n",
    "        filtered_df[\"Region\"].isin(regions)\n",
    "    ]\n",
    "\n",
    "st.success(f\"Showing {len(filtered_df)} records\")\n",
    "\n",
    "# ==========================================\n",
    "# Dataset Preview\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"Dataset Preview\")\n",
    "\n",
    "st.dataframe(\n",
    "    filtered_df,\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Sales by Category\n",
    "# ==========================================\n",
    "\n",
    "if {\"Category\",\"Sales\"}.issubset(filtered_df.columns):\n",
    "\n",
    "    st.subheader(\"Sales by Category\")\n",
    "\n",
    "    sales_category = (\n",
    "        filtered_df\n",
    "        .groupby(\"Category\")[\"Sales\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.bar(\n",
    "        sales_category,\n",
    "        x=\"Category\",\n",
    "        y=\"Sales\",\n",
    "        color=\"Category\",\n",
    "        text_auto=True\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ==========================================\n",
    "# Profit by Region\n",
    "# ==========================================\n",
    "\n",
    "if {\"Region\",\"Profit\"}.issubset(filtered_df.columns):\n",
    "\n",
    "    st.subheader(\"Profit by Region\")\n",
    "\n",
    "    region_profit = (\n",
    "        filtered_df\n",
    "        .groupby(\"Region\")[\"Profit\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.pie(\n",
    "        region_profit,\n",
    "        names=\"Region\",\n",
    "        values=\"Profit\",\n",
    "        hole=0.4\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ==========================================\n",
    "# Payment Method Distribution\n",
    "# ==========================================\n",
    "\n",
    "if \"Payment Method\" in filtered_df.columns:\n",
    "\n",
    "    st.subheader(\"Payment Method Distribution\")\n",
    "\n",
    "    fig = px.histogram(\n",
    "        filtered_df,\n",
    "        x=\"Payment Method\",\n",
    "        color=\"Payment Method\"\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ==========================================\n",
    "# Customer Rating Distribution\n",
    "# ==========================================\n",
    "\n",
    "if \"Customer Rating\" in filtered_df.columns:\n",
    "\n",
    "    st.subheader(\"Customer Rating\")\n",
    "\n",
    "    fig = px.histogram(\n",
    "        filtered_df,\n",
    "        x=\"Customer Rating\",\n",
    "        nbins=10\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ==========================================\n",
    "# Sales vs Profit\n",
    "# ==========================================\n",
    "\n",
    "if {\"Sales\",\"Profit\"}.issubset(filtered_df.columns):\n",
    "\n",
    "    st.subheader(\"Sales vs Profit\")\n",
    "\n",
    "    fig = px.scatter(\n",
    "        filtered_df,\n",
    "        x=\"Sales\",\n",
    "        y=\"Profit\",\n",
    "        color=\"Category\" if \"Category\" in filtered_df.columns else None,\n",
    "        hover_data=filtered_df.columns\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ==========================================\n",
    "# Top Products\n",
    "# ==========================================\n",
    "\n",
    "if {\"Product Name\",\"Sales\"}.issubset(filtered_df.columns):\n",
    "\n",
    "    st.subheader(\"Top 10 Products\")\n",
    "\n",
    "    top_products = (\n",
    "        filtered_df\n",
    "        .groupby(\"Product Name\")[\"Sales\"]\n",
    "        .sum()\n",
    "        .sort_values(ascending=False)\n",
    "        .head(10)\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.bar(\n",
    "        top_products,\n",
    "        x=\"Sales\",\n",
    "        y=\"Product Name\",\n",
    "        orientation=\"h\",\n",
    "        text_auto=True\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9a268c6-3b08-4140-90b4-b68b51075d53",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import os\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Business KPI Dashboard\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"📊 Business KPI Dashboard\")\n",
    "st.write(\"Monitor your business performance using real-time KPIs.\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Load Dataset\n",
    "# ==========================================\n",
    "\n",
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"]\n",
    "\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")\n",
    "\n",
    "else:\n",
    "    st.warning(\"Please upload a dataset first.\")\n",
    "    st.stop()\n",
    "\n",
    "# ==========================================\n",
    "# Convert Date\n",
    "# ==========================================\n",
    "\n",
    "if \"Order Date\" in df.columns:\n",
    "    df[\"Order Date\"] = pd.to_datetime(df[\"Order Date\"])\n",
    "\n",
    "# ==========================================\n",
    "# KPI Calculations\n",
    "# ==========================================\n",
    "\n",
    "total_sales = df[\"Sales\"].sum()\n",
    "total_profit = df[\"Profit\"].sum()\n",
    "total_orders = len(df)\n",
    "total_customers = df[\"Customer ID\"].nunique()\n",
    "average_order = df[\"Sales\"].mean()\n",
    "average_rating = df[\"Customer Rating\"].mean()\n",
    "\n",
    "# ==========================================\n",
    "# KPI Cards\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"Executive Overview\")\n",
    "\n",
    "c1,c2,c3 = st.columns(3)\n",
    "\n",
    "c1.metric(\n",
    "    \"💰 Total Sales\",\n",
    "    f\"${total_sales:,.2f}\"\n",
    ")\n",
    "\n",
    "c2.metric(\n",
    "    \"📈 Total Profit\",\n",
    "    f\"${total_profit:,.2f}\"\n",
    ")\n",
    "\n",
    "c3.metric(\n",
    "    \"📦 Total Orders\",\n",
    "    f\"{total_orders:,}\"\n",
    ")\n",
    "\n",
    "c4,c5,c6 = st.columns(3)\n",
    "\n",
    "c4.metric(\n",
    "    \"👥 Customers\",\n",
    "    total_customers\n",
    ")\n",
    "\n",
    "c5.metric(\n",
    "    \"🛒 Average Order Value\",\n",
    "    f\"${average_order:,.2f}\"\n",
    ")\n",
    "\n",
    "c6.metric(\n",
    "    \"⭐ Average Rating\",\n",
    "    f\"{average_rating:.2f}\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Monthly Sales Trend\n",
    "# ==========================================\n",
    "\n",
    "if \"Order Date\" in df.columns:\n",
    "\n",
    "    monthly = (\n",
    "        df\n",
    "        .groupby(df[\"Order Date\"].dt.to_period(\"M\"))[\"Sales\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    monthly[\"Order Date\"] = monthly[\"Order Date\"].astype(str)\n",
    "\n",
    "    fig = px.line(\n",
    "        monthly,\n",
    "        x=\"Order Date\",\n",
    "        y=\"Sales\",\n",
    "        markers=True,\n",
    "        title=\"Monthly Sales Trend\"\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Top 10 Customers\n",
    "# ==========================================\n",
    "\n",
    "if {\"Customer Name\",\"Sales\"}.issubset(df.columns):\n",
    "\n",
    "    st.subheader(\"Top Customers\")\n",
    "\n",
    "    top_customers = (\n",
    "        df.groupby(\"Customer Name\")[\"Sales\"]\n",
    "        .sum()\n",
    "        .sort_values(ascending=False)\n",
    "        .head(10)\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.bar(\n",
    "        top_customers,\n",
    "        x=\"Sales\",\n",
    "        y=\"Customer Name\",\n",
    "        orientation=\"h\",\n",
    "        text_auto=True\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Top Products\n",
    "# ==========================================\n",
    "\n",
    "if {\"Product Name\",\"Sales\"}.issubset(df.columns):\n",
    "\n",
    "    st.subheader(\"Best Selling Products\")\n",
    "\n",
    "    top_products = (\n",
    "        df.groupby(\"Product Name\")[\"Sales\"]\n",
    "        .sum()\n",
    "        .sort_values(ascending=False)\n",
    "        .head(10)\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.bar(\n",
    "        top_products,\n",
    "        x=\"Sales\",\n",
    "        y=\"Product Name\",\n",
    "        orientation=\"h\",\n",
    "        text_auto=True,\n",
    "        color=\"Sales\"\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Region Performance\n",
    "# ==========================================\n",
    "\n",
    "if {\"Region\",\"Sales\"}.issubset(df.columns):\n",
    "\n",
    "    st.subheader(\"Regional Sales\")\n",
    "\n",
    "    region = (\n",
    "        df.groupby(\"Region\")[\"Sales\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.pie(\n",
    "        region,\n",
    "        names=\"Region\",\n",
    "        values=\"Sales\",\n",
    "        hole=0.45\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Category Performance\n",
    "# ==========================================\n",
    "\n",
    "if {\"Category\",\"Profit\"}.issubset(df.columns):\n",
    "\n",
    "    st.subheader(\"Category Profit\")\n",
    "\n",
    "    category = (\n",
    "        df.groupby(\"Category\")[\"Profit\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    fig = px.bar(\n",
    "        category,\n",
    "        x=\"Category\",\n",
    "        y=\"Profit\",\n",
    "        color=\"Category\",\n",
    "        text_auto=True\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Discount Analysis\n",
    "# ==========================================\n",
    "\n",
    "if {\"Discount\",\"Profit\"}.issubset(df.columns):\n",
    "\n",
    "    st.subheader(\"Discount vs Profit\")\n",
    "\n",
    "    fig = px.scatter(\n",
    "        df,\n",
    "        x=\"Discount\",\n",
    "        y=\"Profit\",\n",
    "        color=\"Category\",\n",
    "        hover_data=[\"Product Name\"]\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Download KPI Report\n",
    "# ==========================================\n",
    "\n",
    "report = pd.DataFrame({\n",
    "    \"Metric\":[\n",
    "        \"Total Sales\",\n",
    "        \"Total Profit\",\n",
    "        \"Total Orders\",\n",
    "        \"Customers\",\n",
    "        \"Average Order Value\",\n",
    "        \"Average Rating\"\n",
    "    ],\n",
    "    \"Value\":[\n",
    "        total_sales,\n",
    "        total_profit,\n",
    "        total_orders,\n",
    "        total_customers,\n",
    "        average_order,\n",
    "        average_rating\n",
    "    ]\n",
    "})\n",
    "\n",
    "csv = report.to_csv(index=False).encode()\n",
    "\n",
    "st.download_button(\n",
    "    \"📥 Download KPI Report\",\n",
    "    csv,\n",
    "    \"KPI_Report.csv\",\n",
    "    \"text/csv\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a3aefdbe-7f1a-4c4f-afb7-ad2bbf25be8c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"AI Business Assistant\",\n",
    "    page_icon=\"🤖\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"🤖 AI Business Assistant\")\n",
    "\n",
    "st.write(\n",
    "    \"Ask business questions about your uploaded dataset.\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Load Dataset\n",
    "# ==========================================\n",
    "\n",
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"]\n",
    "\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")\n",
    "\n",
    "else:\n",
    "    st.warning(\"Please upload a dataset first.\")\n",
    "    st.stop()\n",
    "\n",
    "# ==========================================\n",
    "# Sample Questions\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"💡 Sample Questions\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "• Total Sales\n",
    "\n",
    "• Total Profit\n",
    "\n",
    "• Total Orders\n",
    "\n",
    "• Total Customers\n",
    "\n",
    "• Average Customer Rating\n",
    "\n",
    "• Top 5 Products\n",
    "\n",
    "• Top 5 Customers\n",
    "\n",
    "• Best Category\n",
    "\n",
    "• Best Region\n",
    "\n",
    "• Highest Profit\n",
    "\n",
    "• Lowest Profit\n",
    "\n",
    "• Dataset Shape\n",
    "\"\"\")\n",
    "\n",
    "question = st.text_input(\n",
    "    \"Ask your question\"\n",
    ")\n",
    "\n",
    "if st.button(\"Get Answer\"):\n",
    "\n",
    "    q = question.lower()\n",
    "\n",
    "    answer = \"Sorry, I don't understand that question.\"\n",
    "\n",
    "    if \"total sales\" in q:\n",
    "        answer = f\"💰 Total Sales = ${df['Sales'].sum():,.2f}\"\n",
    "\n",
    "    elif \"total profit\" in q:\n",
    "        answer = f\"📈 Total Profit = ${df['Profit'].sum():,.2f}\"\n",
    "\n",
    "    elif \"orders\" in q:\n",
    "        answer = f\"📦 Total Orders = {len(df)}\"\n",
    "\n",
    "    elif \"customers\" in q:\n",
    "        answer = f\"👥 Total Customers = {df['Customer ID'].nunique()}\"\n",
    "\n",
    "    elif \"rating\" in q:\n",
    "        answer = f\"⭐ Average Rating = {df['Customer Rating'].mean():.2f}\"\n",
    "\n",
    "    elif \"top 5 products\" in q:\n",
    "\n",
    "        top = (\n",
    "            df.groupby(\"Product Name\")[\"Sales\"]\n",
    "            .sum()\n",
    "            .sort_values(ascending=False)\n",
    "            .head(5)\n",
    "        )\n",
    "\n",
    "        answer = top\n",
    "\n",
    "    elif \"top 5 customers\" in q:\n",
    "\n",
    "        top = (\n",
    "            df.groupby(\"Customer Name\")[\"Sales\"]\n",
    "            .sum()\n",
    "            .sort_values(ascending=False)\n",
    "            .head(5)\n",
    "        )\n",
    "\n",
    "        answer = top\n",
    "\n",
    "    elif \"best category\" in q:\n",
    "\n",
    "        answer = (\n",
    "            df.groupby(\"Category\")[\"Sales\"]\n",
    "            .sum()\n",
    "            .idxmax()\n",
    "        )\n",
    "\n",
    "    elif \"best region\" in q:\n",
    "\n",
    "        answer = (\n",
    "            df.groupby(\"Region\")[\"Sales\"]\n",
    "            .sum()\n",
    "            .idxmax()\n",
    "        )\n",
    "\n",
    "    elif \"highest profit\" in q:\n",
    "\n",
    "        answer = df[\"Profit\"].max()\n",
    "\n",
    "    elif \"lowest profit\" in q:\n",
    "\n",
    "        answer = df[\"Profit\"].min()\n",
    "\n",
    "    elif \"shape\" in q:\n",
    "\n",
    "        answer = f\"Rows = {df.shape[0]}, Columns = {df.shape[1]}\"\n",
    "\n",
    "    st.success(answer)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Dataset Preview\n",
    "# ==========================================\n",
    "\n",
    "with st.expander(\"View Dataset\"):\n",
    "\n",
    "    st.dataframe(\n",
    "        df,\n",
    "        use_container_width=True\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5541b37a-683c-4678-ba27-ca831cd8e590",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import plotly.express as px\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import (\n",
    "    mean_absolute_error,\n",
    "    mean_squared_error,\n",
    "    r2_score\n",
    ")\n",
    "\n",
    "import joblib\n",
    "\n",
    "# ======================================\n",
    "# Page Config\n",
    "# ======================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Sales Forecasting\",\n",
    "    page_icon=\"📈\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"📈 AI Sales Forecasting\")\n",
    "\n",
    "st.write(\n",
    "    \"Train a Machine Learning model to predict sales.\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ======================================\n",
    "# Load Dataset\n",
    "# ======================================\n",
    "\n",
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"]\n",
    "\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")\n",
    "\n",
    "else:\n",
    "    st.warning(\"Please upload dataset first.\")\n",
    "    st.stop()\n",
    "\n",
    "# ======================================\n",
    "# Feature Selection\n",
    "# ======================================\n",
    "\n",
    "numeric_columns = df.select_dtypes(include=np.number).columns.tolist()\n",
    "\n",
    "target = st.selectbox(\n",
    "    \"Target Column\",\n",
    "    numeric_columns,\n",
    "    index=numeric_columns.index(\"Sales\")\n",
    "    if \"Sales\" in numeric_columns else 0\n",
    ")\n",
    "\n",
    "features = st.multiselect(\n",
    "    \"Select Feature Columns\",\n",
    "    [c for c in numeric_columns if c != target],\n",
    "    default=[c for c in numeric_columns if c != target]\n",
    ")\n",
    "\n",
    "if len(features) == 0:\n",
    "    st.warning(\"Select at least one feature.\")\n",
    "    st.stop()\n",
    "\n",
    "# ======================================\n",
    "# Train Model\n",
    "# ======================================\n",
    "\n",
    "if st.button(\"🚀 Train Model\"):\n",
    "\n",
    "    X = df[features]\n",
    "    y = df[target]\n",
    "\n",
    "    X_train, X_test, y_train, y_test = train_test_split(\n",
    "        X,\n",
    "        y,\n",
    "        test_size=0.2,\n",
    "        random_state=42\n",
    "    )\n",
    "\n",
    "    model = LinearRegression()\n",
    "\n",
    "    model.fit(X_train, y_train)\n",
    "\n",
    "    prediction = model.predict(X_test)\n",
    "\n",
    "    # Save Model\n",
    "    os.makedirs(\"models\", exist_ok=True)\n",
    "    joblib.dump(model, \"models/sales_model.pkl\")\n",
    "\n",
    "    # Metrics\n",
    "    mae = mean_absolute_error(y_test, prediction)\n",
    "    rmse = np.sqrt(mean_squared_error(y_test, prediction))\n",
    "    r2 = r2_score(y_test, prediction)\n",
    "\n",
    "    st.success(\"Model Trained Successfully!\")\n",
    "\n",
    "    c1, c2, c3 = st.columns(3)\n",
    "\n",
    "    c1.metric(\"MAE\", f\"{mae:.2f}\")\n",
    "    c2.metric(\"RMSE\", f\"{rmse:.2f}\")\n",
    "    c3.metric(\"R² Score\", f\"{r2:.4f}\")\n",
    "\n",
    "    st.divider()\n",
    "\n",
    "    # ======================================\n",
    "    # Actual vs Predicted\n",
    "    # ======================================\n",
    "\n",
    "    result = pd.DataFrame({\n",
    "        \"Actual\": y_test,\n",
    "        \"Predicted\": prediction\n",
    "    })\n",
    "\n",
    "    fig = px.scatter(\n",
    "        result,\n",
    "        x=\"Actual\",\n",
    "        y=\"Predicted\",\n",
    "        title=\"Actual vs Predicted Sales\"\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    st.divider()\n",
    "\n",
    "    st.subheader(\"Prediction Results\")\n",
    "\n",
    "    st.dataframe(result.head(20))\n",
    "\n",
    "    # ======================================\n",
    "    # Download Model\n",
    "    # ======================================\n",
    "\n",
    "    with open(\"models/sales_model.pkl\", \"rb\") as file:\n",
    "\n",
    "        st.download_button(\n",
    "            \"⬇ Download Trained Model\",\n",
    "            file,\n",
    "            \"sales_model.pkl\"\n",
    "        )\n",
    "\n",
    "# ======================================\n",
    "# Manual Prediction\n",
    "# ======================================\n",
    "\n",
    "st.divider()\n",
    "\n",
    "st.header(\"🔮 Predict New Sale\")\n",
    "\n",
    "if os.path.exists(\"models/sales_model.pkl\"):\n",
    "\n",
    "    model = joblib.load(\"models/sales_model.pkl\")\n",
    "\n",
    "    values = []\n",
    "\n",
    "    cols = st.columns(len(features))\n",
    "\n",
    "    for i, feature in enumerate(features):\n",
    "\n",
    "        value = cols[i].number_input(\n",
    "            feature,\n",
    "            value=float(df[feature].mean())\n",
    "        )\n",
    "\n",
    "        values.append(value)\n",
    "\n",
    "    if st.button(\"Predict Sale\"):\n",
    "\n",
    "        input_df = pd.DataFrame([values], columns=features)\n",
    "\n",
    "        prediction = model.predict(input_df)[0]\n",
    "\n",
    "        st.success(\n",
    "            f\"Predicted Sale = ${prediction:,.2f}\"\n",
    "        )\n",
    "\n",
    "else:\n",
    "\n",
    "    st.info(\"Train the model first.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ed7cf39-dfba-4920-972b-39763d5f856c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import mysql.connector\n",
    "\n",
    "# ==========================================\n",
    "# Page Configuration\n",
    "# ==========================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"MySQL Integration\",\n",
    "    page_icon=\"🗄️\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"🗄️ MySQL Database Integration\")\n",
    "\n",
    "st.write(\n",
    "    \"Connect to your MySQL database and execute SQL queries.\"\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Sidebar Connection Details\n",
    "# ==========================================\n",
    "\n",
    "st.sidebar.header(\"Database Connection\")\n",
    "\n",
    "host = st.sidebar.text_input(\"Host\", \"localhost\")\n",
    "port = st.sidebar.number_input(\"Port\", value=3306)\n",
    "user = st.sidebar.text_input(\"Username\", \"root\")\n",
    "password = st.sidebar.text_input(\"Password\", type=\"password\")\n",
    "database = st.sidebar.text_input(\"Database Name\")\n",
    "\n",
    "# ==========================================\n",
    "# Connect\n",
    "# ==========================================\n",
    "\n",
    "if st.sidebar.button(\"Connect Database\"):\n",
    "\n",
    "    try:\n",
    "\n",
    "        connection = mysql.connector.connect(\n",
    "            host=host,\n",
    "            port=port,\n",
    "            user=user,\n",
    "            password=password,\n",
    "            database=database\n",
    "        )\n",
    "\n",
    "        st.session_state[\"connection\"] = connection\n",
    "\n",
    "        st.success(\"Database Connected Successfully!\")\n",
    "\n",
    "    except Exception as e:\n",
    "\n",
    "        st.error(e)\n",
    "\n",
    "# ==========================================\n",
    "# SQL Query\n",
    "# ==========================================\n",
    "\n",
    "if \"connection\" in st.session_state:\n",
    "\n",
    "    connection = st.session_state[\"connection\"]\n",
    "\n",
    "    st.subheader(\"Execute SQL Query\")\n",
    "\n",
    "    query = st.text_area(\n",
    "        \"Write SQL Query\",\n",
    "        \"SELECT * FROM Orders;\"\n",
    "    )\n",
    "\n",
    "    if st.button(\"Run Query\"):\n",
    "\n",
    "        try:\n",
    "\n",
    "            cursor = connection.cursor()\n",
    "\n",
    "            cursor.execute(query)\n",
    "\n",
    "            result = cursor.fetchall()\n",
    "\n",
    "            columns = [i[0] for i in cursor.description]\n",
    "\n",
    "            df = pd.DataFrame(result, columns=columns)\n",
    "\n",
    "            st.dataframe(\n",
    "                df,\n",
    "                use_container_width=True\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "\n",
    "            st.error(e)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ==========================================\n",
    "# Sample Queries\n",
    "# ==========================================\n",
    "\n",
    "st.subheader(\"Sample Queries\")\n",
    "\n",
    "st.code(\"\"\"\n",
    "\n",
    "SELECT * FROM Orders;\n",
    "\n",
    "SELECT Category,\n",
    "SUM(Sales)\n",
    "FROM Orders\n",
    "GROUP BY Category;\n",
    "\n",
    "SELECT Region,\n",
    "SUM(Profit)\n",
    "FROM Orders\n",
    "GROUP BY Region;\n",
    "\n",
    "SELECT *\n",
    "FROM Orders\n",
    "ORDER BY Sales DESC\n",
    "LIMIT 10;\n",
    "\n",
    "\"\"\", language=\"sql\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "588e9d4b-2995-4aaa-a5c1-a29dd79dd8a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"About\",\n",
    "    page_icon=\"ℹ️\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"ℹ️ About This Project\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "# AI-Powered E-Commerce Analytics & Sales Forecasting Platform\n",
    "\n",
    "### Final Year Data Science Project\n",
    "\n",
    "## Project Overview\n",
    "\n",
    "This application provides an end-to-end solution for e-commerce data analysis.\n",
    "\n",
    "### Key Features\n",
    "\n",
    "- 📂 Dataset Upload\n",
    "- 🧹 Data Cleaning\n",
    "- 📊 Exploratory Data Analysis\n",
    "- 📈 KPI Dashboard\n",
    "- 🤖 AI Business Assistant\n",
    "- 🔮 Sales Forecasting\n",
    "- 🗄️ MySQL Integration\n",
    "\n",
    "## Technologies Used\n",
    "\n",
    "- Python\n",
    "- Streamlit\n",
    "- Pandas\n",
    "- NumPy\n",
    "- Plotly\n",
    "- Scikit-learn\n",
    "- MySQL\n",
    "- Joblib\n",
    "\n",
    "## Developed By\n",
    "\n",
    "**Deepak Bailwal**\n",
    "\n",
    "B.Com (DU SOL)\n",
    "\n",
    "Data Science Student\n",
    "\n",
    "## Version\n",
    "\n",
    "1.0\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38ceaae6-c302-4502-bf20-614ab74cdde2",
   "metadata": {},
   "outputs": [],
   "source": [
    "if \"df\" in st.session_state:\n",
    "    df = st.session_state[\"df\"]\n",
    "elif os.path.exists(\"data/ecommerce.csv\"):\n",
    "    df = pd.read_csv(\"data/ecommerce.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7fba8924-23f6-4ffc-8d64-915c6138f2fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "from utils.data_loader import load_data\n",
    "\n",
    "df = load_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "276b8cec-865d-4b05-ae43-58908e9a90e4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
